### ISSUE TITLE
  相机不允许使用时，打开扫码功能会闪退

### ISSUE THREAD

**Issue by aq09312201** [xuzhongpeng/qrcode_flutter#10]
crash

**Comment by xuzhongpeng** [comment]
你说的是比如在模拟器上时，打开了扫码会闪退吧。目前是这样，你必须保证您的手机上有相机才能尝试打开本库的扫码相机，如果没有的情况下需要您自己判断加载内容，不然相机内容显示的地方就不知道如何定义了。你看是否解决了你的问题

**Comment by aq09312201** [comment]
nonono,在真机上，如果真机不允许访问拍照权限，直接崩到sdk里面去了，sdk里面没有判断权限

**Comment by xuzhongpeng** [comment]
> nonono,在真机上，如果真机不允许访问拍照权限，直接崩到sdk里面去了，sdk里面没有判断权限

请提供一下复现机型，我在小米9手机上测试没有问题

**Comment by aq09312201** [comment]
iPhone x设备，应该是所有ios设备

**Comment by xuzhongpeng** [comment]
> iPhone x设备，应该是所有ios设备

fix in 2.0.0
