### ISSUE TITLE
/Users/fjlead/.pub-cache/hosted/pub.flutter-io.cn/qrcode_flutter-2.0.0/android/build.gradle' line: 25

### ISSUE THREAD

**Issue by YelenaLemon** [xuzhongpeng/qrcode_flutter#11]
Log:
FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* Where:
Build file '/Users/fjlead/.pub-cache/hosted/pub.flutter-io.cn/qrcode_flutter-2.0.0/android/build.gradle' line: 25

* What went wrong:
A problem occurred evaluating project ':qrcode_flutter'.
> Could not initialize class org.jetbrains.kotlin.gradle.plugin.sources.DefaultKotlinSourceSetKt

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* Where:
Script '/Users/fjlead/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 326

* What went wrong:
A problem occurred configuring project ':qrcode_flutter'.
> Failed to notify project evaluation listener.
   > Could not initialize class org.jetbrains.kotlin.gradle.plugin.sources.DefaultKotlinSourceSetKt
   > compileSdkVersion is not specified. Please add it to build.gradle

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
Exception: Gradle task assembleDebug failed with exit code 1

谁遇到过么？

**Comment by xyzbilal** [comment]
same error here

**Comment by xuzhongpeng** [comment]
Maybe you can solve the problem [here](https://stackoverflow.com/questions/61714619/detox-could-not-initialize-class-defaultkotlinsourcesetkt)
