### ISSUE TITLE
Migrate to null safety

### ISSUE THREAD

**Issue by nilsreichardt** [xuzhongpeng/qrcode_flutter#12]
## Description
All dependencies are migrated to null safety. So we should migrate this package to null safety.

## Resources
* [How to migrate Dart packages to null safety](https://youtu.be/eBr5tlumwlg)
* [Announcing Dart null safety beta](https://medium.com/dartlang/announcing-dart-null-safety-beta-87610fee6730)

**Comment by xuzhongpeng** [comment]
I will do this next month at the latest. Thank you for your suggestion.

**Comment by xuzhongpeng** [comment]
[support to null-safety](https://pub.dev/packages/qrcode_flutter/versions/3.0.0-nullsafety.0)

**Comment by ghost** [comment]
@xuzhongpeng 
Thank your for adding null-safety support!
Do you know why the plugins still shows as non supported on pub?
(only supported on the prerelease?)
