### ISSUE TITLE
升级gradle和kotlin版本后报错！

### ISSUE THREAD

**Issue by genius1212** [xuzhongpeng/qrcode_flutter#15]
报错信息：
Running Gradle task 'assembleDebug'...
e: /Users/novo/.pub-cache/hosted/pub.flutter-io.cn/qrcode_flutter-2.0.1/android/src/main/kotlin/com/xzp/qrcode_flutter/QRCaptureView.kt: (120, 17): Object is not abstract and does not implement abstract member public abstract fun onActivityPaused(p0: Activity): Unit defined in android.app.Application.ActivityLifecycleCallbacks
e: /Users/novo/.pub-cache/hosted/pub.flutter-io.cn/qrcode_flutter-2.0.1/android/src/main/kotlin/com/xzp/qrcode_flutter/QRCaptureView.kt: (121, 21): 'onActivityPaused' overrides nothing
e: /Users/novo/.pub-cache/hosted/pub.flutter-io.cn/qrcode_flutter-2.0.1/android/src/main/kotlin/com/xzp/qrcode_flutter/QRCaptureView.kt: (127, 21): 'onActivityResumed' overrides nothing
e: /Users/novo/.pub-cache/hosted/pub.flutter-io.cn/qrcode_flutter-2.0.1/android/src/main/kotlin/com/xzp/qrcode_flutter/QRCaptureView.kt: (133, 21): 'onActivityStarted' overrides nothing
e: /Users/novo/.pub-cache/hosted/pub.flutter-io.cn/qrcode_flutter-2.0.1/android/src/main/kotlin/com/xzp/qrcode_flutter/QRCaptureView.kt: (136, 21): 'onActivityDestroyed' overrides nothing
e: /Users/novo/.pub-cache/hosted/pub.flutter-io.cn/qrcode_flutter-2.0.1/android/src/main/kotlin/com/xzp/qrcode_flutter/QRCaptureView.kt: (139, 21): 'onActivitySaveInstanceState' overrides nothing
e: /Users/novo/.pub-cache/hosted/pub.flutter-io.cn/qrcode_flutter-2.0.1/android/src/main/kotlin/com/xzp/qrcode_flutter/QRCaptureView.kt: (142, 21): 'onActivityStopped' overrides nothing
e: /Users/novo/.pub-cache/hosted/pub.flutter-io.cn/qrcode_flutter-2.0.1/android/src/main/kotlin/com/xzp/qrcode_flutter/QRCaptureView.kt: (145, 21): 'onActivityCreated' overrides nothing

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':qrcode_flutter:compileDebugKotlin'.
> Compilation error. See log for more details

gradle版本信息：
buildscript {
    ext.kotlin_version = '1.5.21'  // 升级适用multidex
    repositories {
        ...
        maven { url 'https://maven.aliyun.com/repository/google' }
        maven { url 'https://maven.aliyun.com/repository/jcenter' }
        maven { url 'http://maven.aliyun.com/nexus/content/groups/public' }
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:4.1.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        ...
    }
}

flutter版本：
[✓] Flutter (Channel master, 2.6.0-12.0.pre.670, on Mac OS X 10.15.7 19H15 darwin-x64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[!] Xcode - develop for iOS and macOS (Xcode 12.3)
! Flutter recommends a minimum Xcode version of 13.
Download the latest version or update via the Mac App Store.
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.6)
[✓] VS Code (version 1.50.1)
[✓] Connected device (2 available)

**Comment by xuzhongpeng** [comment]
我在example中升级了gradle和kotlin并没有发生你上面的报错，具体可以查看[demo/grade4](https://github.com/xuzhongpeng/qrcode_flutter/tree/demo/grade4)分支，如果还有错误，可以在这个分支上复现后发一个pr，我再看看

**Comment by xuzhongpeng** [comment]
由于很久没有收到反馈，我先关闭这个issue，后续如果还有问题可以再重新打开
