### ISSUE TITLE
Still not for web?

### ISSUE THREAD

**Issue by Kakukaho** [xuzhongpeng/qrcode_flutter#16]
Still not for web?
仍不支持web QR scanner?

**Comment by xuzhongpeng** [comment]
技术上适配成本比较高，年中会专门对这块进行适配

**Comment by rty813** [comment]
我看现在已经有web的摄像头库了，利用那个库获取视频流然后识别，应该不是很难吧？
https://pub.dev/packages/camera_web

**Comment by xuzhongpeng** [comment]
https://pub.dev/packages/qrcode_flutter/3.0.0 割了半年，终于支持Web了，同时将Android和iOS适配了最新3.6
