### ISSUE TITLE
Android can't recognize qr code from gallery when there has Chinese

### ISSUE THREAD

**Issue by asionbo** [xuzhongpeng/qrcode_flutter#2]
相册的二维码中含有中文时，无法识别，应该是这个编码的问题

QrcodeFlutterPlugin--> hints.put(DecodeHintType.CHARACTER_SET, "utf-8"); // 设置二维码内容的编码

**Comment by xuzhongpeng** [comment]
好的 你是说扫描的二维码内容是含有中文是吧

**Comment by asionbo** [comment]
@xuzhongpeng 是的

**Comment by xuzhongpeng** [comment]
> @xuzhongpeng 是的

能给个复现的二维码及操作步骤吗  我测试是正常的

**Comment by asionbo** [comment]
> > @xuzhongpeng 是的
> 
> 能给个复现的二维码及操作步骤吗 我测试是正常的

因为二维码有个人信息，所以单独发送至您的邮箱了，复现步骤：
从相册选择这个二维码来识别，得到的qrCodeResult.size=0.

我也尝试了重新生成含有中文，以及相同信息的二维码是可以识别的，可能不是编码问题。

**Comment by xuzhongpeng** [comment]
> > > @xuzhongpeng 是的
> > 
> > 
> > 能给个复现的二维码及操作步骤吗 我测试是正常的
> 
> 因为二维码有个人信息，所以单独发送至您的邮箱了，复现步骤：
> 从相册选择这个二维码来识别，得到的qrCodeResult.size=0.
> 
> 我也尝试了重新生成含有中文，以及相同信息的二维码是可以识别的，可能不是编码问题。

好的，感谢提交错误，我会尽快修改

**Comment by xuzhongpeng** [comment]
Fixed in 1.0.6
