### ISSUE TITLE
#4002 java.lang.ArithmeticException

### ISSUE THREAD

**Issue by genius1212** [xuzhongpeng/qrcode_flutter#7]
**打开相机时偶发性闪退**

XiaoMi/MIUI

CPU架构   arm64-v8a

#4002 java.lang.ArithmeticException
divide by zero

com.journeyapps.barcodescanner.CameraPreview.void calculateFrames()(SourceFile:11)
解决方案
该异常表示进行算术运算时除零。
[解决方案]：这种异常说明使用了零值做分母，多由于程序员疏忽导致，或者出现在使用第三方控件时未做判断，建议在所有除法运算前检查分母是否为零。

1. com.journeyapps.barcodescanner.CameraPreview.void calculateFrames()(SourceFile:11)
2. com.journeyapps.barcodescanner.CameraPreview.void previewSized(com.journeyapps.barcodescanner.Size)(SourceFile:5)
3. com.journeyapps.barcodescanner.CameraPreview.void access$300(com.journeyapps.barcodescanner.CameraPreview,com.journeyapps.barcodescanner.Size)(SourceFile:1)
4. com.journeyapps.barcodescanner.CameraPreview$3.boolean handleMessage(android.os.Message)(SourceFile:2)
5. android.os.Handler.dispatchMessage(Handler.java:102)
6. android.os.Looper.loop(Looper.java:201)
7. android.app.ActivityThread.main(ActivityThread.java:6806)
8. java.lang.reflect.Method.invoke(Native Method)
9. com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
10. com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

**Comment by genius1212** [comment]
抱歉，我没能找到源码的位置，可能是在静态库里

**Comment by xuzhongpeng** [comment]
> 抱歉，我没能找到源码的位置，可能是在静态库里

请提供一下更详细一点的复现步骤，非常感谢：
1. XiaoMi手机什么型号
2. 打开相机后是否是在扫码过程发生的闪退
3. 闪退的频率大概在多少

**Comment by genius1212** [comment]
感谢回复。

设备机型 小米 MI 8 LITE

是打开相机进行扫码发生闪退，但并未扫取任何二维码，只是在打开的瞬间闪退。

偶发出现：第一次打开，持续停留10s并扫码正常，返回再打开扫码可能出现闪退。

发生概率：重复测试3次，出现2次闪退。
<img width="335" alt="截屏2020-11-20 上午9 35 52" src="https://user-images.githubusercontent.com/59531737/99745382-7f4c9e00-2b14-11eb-8ae7-a9c5f67694e4.png">

**Comment by xuzhongpeng** [comment]
> 感谢回复。
> 
> 设备机型 小米 MI 8 LITE
> 
> 是打开相机进行扫码发生闪退，但并未扫取任何二维码，只是在打开的瞬间闪退。
> 
> 偶发出现：第一次打开，持续停留10s并扫码正常，返回再打开扫码可能出现闪退。
> 
> 发生概率：重复测试3次，出现2次闪退。
> <img alt="截屏2020-11-20 上午9 35 52" width="335" src="https://user-images.githubusercontent.com/59531737/99745382-7f4c9e00-2b14-11eb-8ae7-a9c5f67694e4.png">

好的，我会尽快修复

**Comment by xuzhongpeng** [comment]
如果方便的话请您提供一下测试二维码或者发我邮箱xuzhongpeng@foxmail.com

**Comment by genius1212** [comment]
> 如果方便的话请您提供一下测试二维码或者发我邮箱[xuzhongpeng@foxmail.com](mailto:xuzhongpeng@foxmail.com)

没有进行扫码，只是打开扫码页面即闪退

**Comment by xuzhongpeng** [comment]
> > 如果方便的话请您提供一下测试二维码或者发我邮箱[xuzhongpeng@foxmail.com](mailto:xuzhongpeng@foxmail.com)
> 
> 没有进行扫码，只是打开扫码页面即闪退

因为现有机型没有复现问题，大致知道是zixing库的bug，你可以用我提交的hotfix/7分支看是否已经解决问题，期待你的反馈

**Comment by genius1212** [comment]
> > > 如果方便的话请您提供一下测试二维码或者发我邮箱[xuzhongpeng@foxmail.com](mailto:xuzhongpeng@foxmail.com)
> > 
> > 
> > 没有进行扫码，只是打开扫码页面即闪退
> 
> 因为现有机型没有复现问题，大致知道是zixing库的bug，你可以用我提交的hotfix/7分支看是否已经解决问题，期待你的反馈

实不相瞒，我目前也没有xiaomi8 Lite这个机型，这个问题是打包给小米平台审核测试出来的，我现在再打个包给小米平台测试，这样可能需要几天时间。

感谢及时处理。

**Comment by genius1212** [comment]
更新后，小米测试没有出现闪退，这边可以认为已处理
